/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountSettingsRouteImport } from './routes/account-settings'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin-dashboard/index'
import { Route as AdminDashboardLoginRouteImport } from './routes/admin-dashboard/login'
import { Route as CheckoutBrokerRouteImport } from './routes/checkout/broker'
import { Route as CheckoutDetailsRouteImport } from './routes/checkout/details'
import { Route as CheckoutPaymentMethodRouteImport } from './routes/checkout/payment-method'
import { Route as CheckoutProofRouteImport } from './routes/checkout/proof'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalRiskRouteImport } from './routes/legal.risk'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardLoginRoute = AdminDashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const CheckoutBrokerRoute = CheckoutBrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutDetailsRoute = CheckoutDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPaymentMethodRoute = CheckoutPaymentMethodRouteImport.update({
  id: '/payment-method',
  path: '/payment-method',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutProofRoute = CheckoutProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => CheckoutRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRiskRoute = LegalRiskRouteImport.update({
  id: '/legal/risk',
  path: '/legal/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRouteWithChildren
  '/brokers': typeof BrokersRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/support': typeof SupportRoute
  '/admin-dashboard/login': typeof AdminDashboardLoginRoute
  '/checkout/broker': typeof CheckoutBrokerRoute
  '/checkout/details': typeof CheckoutDetailsRoute
  '/checkout/payment-method': typeof CheckoutPaymentMethodRoute
  '/checkout/proof': typeof CheckoutProofRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/brokers': typeof BrokersRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/support': typeof SupportRoute
  '/admin-dashboard/login': typeof AdminDashboardLoginRoute
  '/checkout/broker': typeof CheckoutBrokerRoute
  '/checkout/details': typeof CheckoutDetailsRoute
  '/checkout/payment-method': typeof CheckoutPaymentMethodRoute
  '/checkout/proof': typeof CheckoutProofRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRouteWithChildren
  '/brokers': typeof BrokersRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/support': typeof SupportRoute
  '/admin-dashboard/login': typeof AdminDashboardLoginRoute
  '/checkout/broker': typeof CheckoutBrokerRoute
  '/checkout/details': typeof CheckoutDetailsRoute
  '/checkout/payment-method': typeof CheckoutPaymentMethodRoute
  '/checkout/proof': typeof CheckoutProofRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-settings'
    | '/accounts'
    | '/admin'
    | '/admin-dashboard'
    | '/brokers'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/reviews'
    | '/support'
    | '/admin-dashboard/login'
    | '/checkout/broker'
    | '/checkout/details'
    | '/checkout/payment-method'
    | '/checkout/proof'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/risk'
    | '/legal/terms'
    | '/admin-dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-settings'
    | '/accounts'
    | '/admin'
    | '/brokers'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/reviews'
    | '/support'
    | '/admin-dashboard/login'
    | '/checkout/broker'
    | '/checkout/details'
    | '/checkout/payment-method'
    | '/checkout/proof'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/risk'
    | '/legal/terms'
    | '/admin-dashboard'
  id:
    | '__root__'
    | '/'
    | '/account-settings'
    | '/accounts'
    | '/admin'
    | '/admin-dashboard'
    | '/brokers'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/reviews'
    | '/support'
    | '/admin-dashboard/login'
    | '/checkout/broker'
    | '/checkout/details'
    | '/checkout/payment-method'
    | '/checkout/proof'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/risk'
    | '/legal/terms'
    | '/admin-dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountsRoute: typeof AccountsRoute
  AdminRoute: typeof AdminRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  BrokersRoute: typeof BrokersRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  ReviewsRoute: typeof ReviewsRoute
  SupportRoute: typeof SupportRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalRiskRoute: typeof LegalRiskRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-settings': {
      id: '/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/': {
      id: '/admin-dashboard/'
      path: '/'
      fullPath: '/admin-dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin-dashboard/login': {
      id: '/admin-dashboard/login'
      path: '/login'
      fullPath: '/admin-dashboard/login'
      preLoaderRoute: typeof AdminDashboardLoginRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/checkout/broker': {
      id: '/checkout/broker'
      path: '/broker'
      fullPath: '/checkout/broker'
      preLoaderRoute: typeof CheckoutBrokerRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/details': {
      id: '/checkout/details'
      path: '/details'
      fullPath: '/checkout/details'
      preLoaderRoute: typeof CheckoutDetailsRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/payment-method': {
      id: '/checkout/payment-method'
      path: '/payment-method'
      fullPath: '/checkout/payment-method'
      preLoaderRoute: typeof CheckoutPaymentMethodRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/proof': {
      id: '/checkout/proof'
      path: '/proof'
      fullPath: '/checkout/proof'
      preLoaderRoute: typeof CheckoutProofRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/risk': {
      id: '/legal/risk'
      path: '/legal/risk'
      fullPath: '/legal/risk'
      preLoaderRoute: typeof LegalRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardLoginRoute: typeof AdminDashboardLoginRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardLoginRoute: AdminDashboardLoginRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutBrokerRoute: typeof CheckoutBrokerRoute
  CheckoutDetailsRoute: typeof CheckoutDetailsRoute
  CheckoutPaymentMethodRoute: typeof CheckoutPaymentMethodRoute
  CheckoutProofRoute: typeof CheckoutProofRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutBrokerRoute: CheckoutBrokerRoute,
  CheckoutDetailsRoute: CheckoutDetailsRoute,
  CheckoutPaymentMethodRoute: CheckoutPaymentMethodRoute,
  CheckoutProofRoute: CheckoutProofRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountsRoute: AccountsRoute,
  AdminRoute: AdminRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  BrokersRoute: BrokersRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  ReviewsRoute: ReviewsRoute,
  SupportRoute: SupportRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalRiskRoute: LegalRiskRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
